# Generated by Django 5.1.5 on 2025-01-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_content',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Article', 'Article'), ('Quiz', 'Quiz')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_preference',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Night', 'Night')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_year_level',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], max_length=20, null=True),
        ),
    ]
