# Generated by Django 5.1.5 on 2025-03-08 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_preferred_content_user_study_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=2000)),
                ('text', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('top_image', models.URLField(blank=True, max_length=2000, null=True)),
                ('meta_description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
