# Generated by Django 5.1.5 on 2025-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
