# Generated by Django 5.1.5 on 2025-03-19 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

def set_default_created_at(apps, schema_editor):
    Article = apps.get_model('account', 'Article')
    for article in Article.objects.all():
        if article.created_at is None:
            article.created_at = timezone.now()
            article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_article_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(set_default_created_at, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='account.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('article', 'user')},
            },
        ),
    ]
